# Use slim Python 3.10 image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy app code
COPY glconnect /app/glconnect
COPY requirements.txt .

# Install dependencies inside the container
RUN pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 8001

# Run the app
CMD ["uvicorn", "glconnect.voc:app", "--host", "0.0.0.0", "--port", "8001"]



