server {
    listen 80;
    server_name www.glc.cool glc.cool;

    # Serve the challenge files for Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect all HTTP traffic to HTTPS (non-www version as canonical)
    location / {
        return 301 https://glc.cool$request_uri;  # Redirect www to non-www (or vice versa)
    }
}

server {
    listen 443 ssl;
    server_name www.glc.cool glc.cool;

    ssl_certificate /etc/letsencrypt/live/www.glc.cool/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.glc.cool/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256';
    ssl_prefer_server_ciphers on;

    # Add SSL security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy no-referrer-when-downgrade always;

    # Proxy to your backend app (Flask or other)
    location / {
        proxy_pass http://myapp:5000; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Proxy requests to /station to the Icecast service
    location /station {
        proxy_pass http://icecast_server:8000/station; 
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /admin {
        proxy_pass http://icecast_server:8000/admin;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
   
    location /art/ {
    proxy_pass http://myapp:5000/art/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Proxy requests to /api for backend services
    location /words {
        proxy_pass http://myapp:5000/words;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
