services:
  - name: app
    type: web  # web type since it's serving a web service
    runtime: docker  # specifying Docker runtime
    image: myapp:latest
    plan: starter
    ports:
      - 5000  # Flask app will be served on port 5000
      - 8001  # Uvicorn app will be served on port 8001
    dockerCommand: >
      python run.py & uvicorn glconnect.voc:app --reload --host 0.0.0.0 --port 8001
    environment:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: development
    volumes:
      - mountPath: /usr/src/appdir
        localPath: ./music-1
    dependsOn:
      - icecast2  # ensures icecast2 starts first
    networks:
      - app_network  # use shared network with icecast2

  - name: icecast2
    type: pserv  # Private service since it's a background service
    runtime: image
    image: deepcomp/icecast2
    plan: starter
    dockerCommand: /usr/bin/icecast -c /etc/icecast.xml -b
    volumes:
      - mountPath: /etc/icecast.xml
        localPath: ./icecast.xml
    networks:
      - app_network  # shared network with app service

  - name: liquidsoap
    type: pserv  # Private service since it's a background service
    runtime: image
    image: phasecorex/liquidsoap:latest
    plan: starter
    dockerCommand: liquidsoap /liqfolder/scripts/main.liq
    volumes:
      - mountPath: /liqfolder
        localPath: ./
    networks:
      - app_network  # shared network with app service

networks:
  app_network:
    driver: bridge
