services:
  - type: web
    name: icecast2
    runtime: image
    image:
      url: deepcomp/icecast2
    plan: starter
    envVars:
      - key: PORT
        value: 8000    

    disk:
      name: icecast-data
      mountPath: /etc/icecast
      sizeGB: 10
