services:
  - type: web
    name: icecast2
    runtime: image
    image:
      url: deepcomp/icecast2  # The image you're using
    plan: starter

    # Mounting a persistent disk to the /etc/conf_files directory
    disk:
      name: icefiles
      mountPath: /etc/conf_files/
      sizeGB: 10

    # Build commands to copy the icecast.xml file from the current directory (cwd)
    buildCommand: |
      # Ensure the icecast.xml file is copied from the current directory (cwd) to the disk's mount path
      cp ./icecast.xml /etc/conf_files/icecast.xml  # Copy icecast.xml to the mounted disk



  